version: 2

project_name: speedtest_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/speedtest_exporter/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
      - ghcr.io/cacack/{{.ProjectName}}:v{{ .Version }}-amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - ghcr.io/cacack/{{.ProjectName}}:v{{ .Version }}-arm64
    use: buildx
    dockerfile: Dockerfile
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:
  - name_template: ghcr.io/cacack/{{.ProjectName}}:v{{ .Version }}
    image_templates:
      - ghcr.io/cacack/{{.ProjectName}}:v{{ .Version }}-amd64
      - ghcr.io/cacack/{{.ProjectName}}:v{{ .Version }}-arm64
  - name_template: ghcr.io/cacack/{{.ProjectName}}:latest
    image_templates:
      - ghcr.io/cacack/{{.ProjectName}}:v{{ .Version }}-amd64
      - ghcr.io/cacack/{{.ProjectName}}:v{{ .Version }}-arm64
